# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: pt-BR

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Cuiaba

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Henrique Sebastião # the main title

tagline: Desenvolvedor back-end # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  Desenvolvedor de software, técnico de redes, músico, entusiasta em hardware, radioamadorismo e segurança.

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://henriquesebastiao.com"

author: henriquesebastiao

github:
  username: henriquesebastiao

# twitter:
#   username:

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Henrique Sebastião
  email: contato@henriquesebastiao.com
  links:
    # The first element serves as the copyright owner's link
    - https://henriquesebastiao.com
    - https://github.com/henriquesebastiao
    - https://www.linkedin.com/in/henriquesebastiao
    - https://bolha.us/@henriquesebastiao

# Site Verification Settings
webmaster_verifications:
  google: B2F5DBVpmj2QL-_8mF2X7e_Bxi_KuMdBeZ1zaKrq9BY
  bing: # fill in your Bing verification code (Not necessary as I already imported from Google Search Console)
  alexa: # fill in your Alexa verification code
  yandex: 2dae2cb40923573a
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: G-BVJ8VX0FC9
  goatcounter:
    id: henriquesebastiao
  umami:
    id: 3a33fd4e-72e9-4dbd-becc-3f0d453ae7cc
    domain: https://umami.henriquesebastiao.com
  matomo:
    id: 1
    domain: https://matomo.henriquesebastiao.com
  cloudflare:
    id: 510965fd9db643a0a76796a949c59d44

# Page views settings
pageviews:
  provider: goatcounter

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode: [dark]

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn: https://imagedelivery.net/UnzHYuseZjpgJ5VEgCbryw

# the avatar on sidebar, support local or CORS resources
avatar: "/2a687c2f-8fab-4347-3bc0-a3cb04d4bb00/public"

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: "/e68eb84b-89e4-4c9c-d805-d71b3ef4dc00/public"

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: [giscus] # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: "henriquesebastiao/henriquesebastiao.com"
    repo_id: "R_kgDOOMK3Bw"
    category: "General"
    category_id: "DIC_kwDOOMK3B84CoYEQ"
    mapping: "pathname" # optional, default to 'pathname'
    strict: # optional, default to '0'
    # input_position: "top" # optional, default to 'bottom'
    # lang: "pt" # optional, default to the value of `site.lang`
    reactions_enabled: "1" # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# The base URL of your site
baseurl: ""

plugins:
  - jekyll-polyglot

# Polyglot Settings
languages: ["pt-BR", "en"]
default_lang: "pt-BR"
exclude_from_localization: ["assets", ".github", ".venv", ".wrangler", "scripts", "pyproject.toml", "poetry.lock", "links"]
parallel_localization: false
lang_from_path: true

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  # - "*.gem"
  - jekyll-theme-chirpy.gemspec # - "*.gemspec"
  - docs
  - scripts
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
  - justfile
  - Dockerfile
  - docker-compose.yml
  - pyproject.toml
  - poetry.lock
  - links

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
