name: Check Bronken Links

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  check-bronken-links:
    runs-on: ubuntu-latest

    steps:
      - name: Copy files from repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Check Bronken Links
        run: python scripts/check_broken_links.py