name: Deploy

on:
  workflow_run:
      workflows: ["Build"]
      types: [completed]
      branches:
          - 'main'

  workflow_dispatch:

permissions:
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download site
        uses: actions/download-artifact@v4
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./_site --project-name=henriquesebastiao --branch=main